### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by hellogirl007** [PromptFuzz/PromptFuzz#3]
when building the dockerfile, the error occurs

 => ERROR [ 9/10] ADD Cargo.lock Cargo.toml /prompt_fuzz/                                                          0.0s
------
 > [ 9/10] ADD Cargo.lock Cargo.toml /prompt_fuzz/:
------
Dockerfile:30
--------------------
  28 |     ADD ./src/ /prompt_fuzz/src
  29 |     ADD ./testsuites /prompt_fuzz/testsuites
  30 | >>> ADD Cargo.lock Cargo.toml /prompt_fuzz/
  31 |     WORKDIR /prompt_fuzz
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref bdb4a551-c262-4283-8f9e-fa58d89e895f::qmv8dpeqgfvsbohju39l44o0y: "/Cargo.lock": not found

**Comment by PromptFuzz** [comment]
@hellogirl007 Fixed in d9e414bbe8e33a6bff22096d2f6b42e3a20abb3a.
