### ISSUE TITLE
Slef-Hosted LLM?

### ISSUE THREAD

**Issue by vsecv** [PromptFuzz/PromptFuzz#4]
Hello,

Is there a way to configure it in an on-premise environment?

Looking at the contents, I think need external API(Ex) ChatGPT).

Is there a way to test in an environment where I can't communicate with the outside world?

I'm looking for a way to fuzz without exposing the data (source code) to the outside.

Will it be possible to use self-hosted LLM like Llama, CodeT5, etc. in the future?

Thanks

**Comment by PromptFuzz** [comment]
@vsecv Yes! It is possible to support self-hosted LLMs. 

Here are two ways to support self-hosted LLMs.
1. Build handlers for local running LLMs.
You can see that in the file `/src/extern/incoder.py`, it implements a local Incoder model which is a kind of self-hosted LLM. 
To support such self-hosted LLMs, we need to implement the corresponding handlers to build pipelines and invoke those LLMs, just like `/src/request/incoder.rs`.
2. Access self-hosted LLMs via REST APIs.
If you can access your self-hosted LLMs via REST APIs which conform to the standards of OPENAI APIs, you only need to set the URL base `OPENAI_PROXY_BASE` to your service location.

Note that the full support of the method 1 is still under development.

**Comment by vsecv** [comment]
@PromptFuzz Thank you for your reply. I will try to refer to the information you sent me! Have a happy day
