### ISSUE TITLE
New Target Build?

### ISSUE THREAD

**Issue by vsecv** [PromptFuzz/PromptFuzz#6]
Hello,

I'm trying to fuzz some new software.(```dlt-daemon```)

I saw Fuzz Drivers developed on oss-fuzz in the path of ``data/lcms/build.sh ``.

In other software, there are Fuzz Drivers created by oss-fuzz as well.

Do I need an existing Fuzz Driver to test the new program?

https://github.com/PromptFuzz/PromptFuzz/blob/0f265751168d98da96d6cee18a24f3fe6a0df215/data/lcms/build.sh#L23-L28

**Comment by PromptFuzz** [comment]
@vsecv 

> I saw Fuzz Drivers developed on oss-fuzz in the path of `data/lcms/build.sh `.

The `build.sh` scripts at the path of `data/project` are used to build the relevant projects and prepare the necessary gadgets.

> Do I need an existing Fuzz Driver to test the new program?

If you just want to test new programs, the answer is **No**. 

We use the "OSS-Fuzz Fuzz Drivers" in the scripts of "build.sh" for experimental comparison. If you don't need a baseline evaluation, the preparation of "OSS-Fuzz Fuzz Drivers" is not neccessary.

**Comment by vsecv** [comment]
@PromptFuzz Thank you for your quick response. I'll refer to what you said and proceed.
